version: "3.9"

services:
  #new app (angular_app)
  angular_app:
    container_name: reactjs_app
    image: pee-react_app:1.0.0
    build: ./react/tasks/
    ports:
      - 4200:4200
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://localhost:3306/tareas_cafe
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: postgres
      MYSQL_DB: tareas_cafe

